server:
  port: 8081
kpro:
  url: https://us-kardia-api-staging.herokuapp.com/i/v1/
  teamId: aexdQsgkXqlpewu1Tb4dcbb80ofl4vje
  username: harpreet.singh+hapifhir7@unthinkable.co
  password: Alivecor1
  socketTimeOut: 6000
  connectionTimeOut: 7000

logging:
  file:
    path: /home/unthinkable-lap-0017/logs/alivecorLogs
  level:
    root: ERROR
    com.hospital: INFO












